name: asistencia
description: Demonstrates how to use the flutter_qr plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  http: ^0.13.3
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  qr_code_scanner:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/bgApp.jpg
    - assets/bgApp2.jpg